-- AlterTable
ALTER TABLE "Layout" ADD COLUMN     "columns" INTEGER NOT NULL DEFAULT 19,
ADD COLUMN     "rows" INTEGER NOT NULL DEFAULT 12,
DROP COLUMN "gridSize",
ADD COLUMN     "gridSize" INTEGER NOT NULL DEFAULT 60;

ALTER TABLE "Layout" ALTER COLUMN "columns" DROP DEFAULT,
ALTER COLUMN "rows" DROP DEFAULT,
ALTER COLUMN "gridSize" DROP DEFAULT;